import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import styles from './index.module.scss';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Frontendmentor intro section</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/images/favicon-32x32.png' />
      </Head>

      <header className={styles.headerMain}>
        <div className={styles.headerLogo}>
          <Image
            src={'/images/logo.svg'}
            width={84}
            height={27}
            alt='snap name logo'
          />
        </div>
        <div className={styles.iconMenu}>
          <Image
            src={'/images/icon-menu.svg'}
            width={32}
            height={18}
            alt='hamburger menu icon'
          />
        </div>
        <nav></nav>
      </header>
      <main>
        <div className={styles.hero}>
          <div className={styles.heroImg}>
            <Image
              src={'/images/image-hero-desktop.png'}
              width={960}
              height={1280}
              alt='boy holding laptop in his hands'
            />
          </div>
          <h1 className={styles.title}>Make remote work</h1>
          <p className={styles.text}>
            Get your team in sync, no matter your loacation. Streamline
            processes, create team rituals, and watch productivity soar.
          </p>
          <button className={styles.btn}>Learn more</button>
          <ul>
            <li>
              <Image
                src={'/images/client-databiz.svg'}
                width={114}
                height={20}
                alt=''
              />
            </li>
            <li>
              <Image
                src={'/images/client-audiophile.svg'}
                width={73}
                height={36}
                alt=''
              />
            </li>
            <li>
              <Image
                src={'/images/client-meet.svg'}
                width={90}
                height={20}
                alt=''
              />
            </li>
            <li>
              <Image
                src={'/images/client-maker.svg'}
                width={83}
                height={24}
                alt=''
              />
            </li>
          </ul>
        </div>
      </main>
    </div>
  );
};

export default Home;
