import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Button from '../components/button/Button';
import Header from '../components/header/Header';

import styles from './index.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.home}>
      <Head>
        <title>Frontendmentor intro section</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='icon'
          type='image/png'
          href='/frontendmentor-intro-music/images/favicon-32x32.png'
        ></link>
      </Head>

      <Header />
      <main className={styles.main}>
        <div className={styles.hero}>
          <div className={styles.heroImg}>
            <Image
              priority={true}
              src='/images/image-hero-mobile.png'
              layout='fill'
              alt='boy holding laptop in his hands'
              objectFit='cover'
              objectPosition='center'
            />
          </div>
          <div className={styles.heroBody}>
            <h1 className={styles.title}>
              <span>Make</span> remote work
            </h1>
            <p className={styles.text}>
              Get your team in sync, no matter your loacation. Streamline
              processes, create team rituals, and watch productivity soar.
            </p>
            <Button variant='contained' href='#'>
              Learn more
            </Button>
            <ul className={styles.list}>
              <li>
                <Image
                  src={'/images/client-databiz.svg'}
                  width={114}
                  layout='responsive'
                  height={20}
                  alt=''
                />
              </li>
              <li>
                <Image
                  src={'/images/client-audiophile.svg'}
                  width={73}
                  layout='responsive'
                  height={36}
                  alt=''
                />
              </li>
              <li>
                <Image
                  src={'/images/client-meet.svg'}
                  width={90}
                  layout='responsive'
                  height={20}
                  alt=''
                />
              </li>
              <li>
                <Image
                  src={'/images/client-maker.svg'}
                  width={83}
                  layout='responsive'
                  height={24}
                  alt=''
                />
              </li>
            </ul>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
