import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/header/Header';

import styles from './index.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.home}>
      <Head>
        <title>Frontendmentor intro section</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/images/favicon-32x32.png' />
      </Head>

      <Header />
      <main className={styles.main}>
        <div className={styles.hero}>
          <div className={styles.heroImg}>
            <Image
              src='/images/image-hero-desktop.png'
              layout='responsive'
              width={960}
              height={1280}
              alt='boy holding laptop in his hands'
            />
          </div>
          <div className={styles.heroBody}>
            <h1 className={styles.title}>Make remote work</h1>
            <p className={styles.text}>
              Get your team in sync, no matter your loacation. Streamline
              processes, create team rituals, and watch productivity soar.
            </p>
            <button className={styles.btn}>Learn more</button>
            <ul className={styles.list}>
              <li>
                <Image
                  src={'/images/client-databiz.svg'}
                  width={114}
                  height={20}
                  alt=''
                />
              </li>
              <li>
                <Image
                  src={'/images/client-audiophile.svg'}
                  width={73}
                  height={36}
                  alt=''
                />
              </li>
              <li>
                <Image
                  src={'/images/client-meet.svg'}
                  width={90}
                  height={20}
                  alt=''
                />
              </li>
              <li>
                <Image
                  src={'/images/client-maker.svg'}
                  width={83}
                  height={24}
                  alt=''
                />
              </li>
            </ul>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
